version: "3"

services:
  auth:
    image: auth:1.0.0
    ports:
      - "50051:50051"
    build: ./auth
    networks:
      - default

  weather:
    image: weather:1.0.0
    ports:
      - "7001:7001"
    build: ./weather
    depends_on:
      - auth
      - twem-proxy
    networks:
      - default
  
  weather-2:
    image: weather:1.0.0
    ports:
      - "7002:7002"
    build: ./weather
    environment:
      - LISTEN_PORT=7002
    depends_on:
      - auth
      - twem-proxy
    networks:
      - default
  
  envoy:
    image: envoyproxy/envoy:dev-6c702f45fadf4abd2f24605e3d9e81c748b13f85
    ports:
      - 8001:8001 
      - 8080:8080
    depends_on:
      - weather
      - weather-2
    networks:
      - default
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  
  redis-1:
    image: 'redis:latest'
    container_name: redis-1
    ports:
      - "6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis-net

  redis-2:
    image: 'redis:latest'
    container_name: redis-2
    ports:
      - "6379"
    volumes:
      - redis_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis-net
  
  redis-3:
    image: 'redis:latest'
    container_name: redis-3
    ports:
      - "6379"
    volumes:
      - redis_3_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" , "--slaveof", "redis-1", "6379" ]
    networks:
      - redis-net

  redis-4:
    image: 'redis:latest'
    container_name: redis-4
    ports:
      - "6379"
    volumes:
      - redis_4_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" , "--slaveof", "redis-2", "6379" ]
    networks:
      - redis-net
  
  twem-proxy:
    image: tarantool/twemproxy
    command:
      - --verbose=11
    volumes:
      - ./nutcracker.yml:/conf/nutcracker.yml
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
    ports:
      - 16379:16379
    networks:
      - redis-net
      - default

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - weather
      - weather-2
    networks:
      - default

networks:
  default:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}
