# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"!\n\x11\x41uthByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x12\x41uthByNameResponse\x12\x0e\n\x06\x61uthed\x18\x01 \x01(\x08\x32K\n\x06\x41uther\x12\x41\n\nAuthByName\x12\x17.auth.AuthByNameRequest\x1a\x18.auth.AuthByNameResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHBYNAMEREQUEST._serialized_start=20
  _AUTHBYNAMEREQUEST._serialized_end=53
  _AUTHBYNAMERESPONSE._serialized_start=55
  _AUTHBYNAMERESPONSE._serialized_end=91
  _AUTHER._serialized_start=93
  _AUTHER._serialized_end=168
# @@protoc_insertion_point(module_scope)
